// Multi-user auth with per-domain access control.
//
// Replaces the single x-brain-key with user-scoped API keys.
// Each key has a username, a set of domain permissions (read/write/admin),
// and an optional global admin flag.
//
// Users are stored in a JSON file at OB2_USERS_FILE (default: ../users.json).
// The file is watched for changes and reloaded automatically.
//
// Key format: "ob2_" + 32-char random hex (generated by create_user CLI).
//
// Permission model:
//   - read:   can search_knowledge, chat_knowledge for a domain
//   - write:  can capture_knowledge into a domain (implies read)
//   - admin:  can delete docs, manage aliases for a domain (implies write)
//   - global_admin: can do anything on any domain, manage users
//
// Backwards compatibility:
//   If OB2_USERS_FILE doesn't exist, falls back to single-key mode
//   (OB2_BRAIN_KEY) — all existing deployments keep working.

import type { Context, MiddlewareHandler } from "hono";
import type { Config } from "./config.ts";
import { hashPassword, verifyPassword as verifyHash } from "./auth/passwords.ts";
import { resolveSession, SESSION_COOKIE_NAME } from "./auth/sessions.ts";

// ─────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────��───────

export type Permission = "read" | "write" | "admin";

export interface UserRecord {
  username: string;
  key: string;
  email?: string;                        // optional recovery email
  password_hash?: string;
  global_admin: boolean;
  domains: Record<string, Permission>;
  created_at: string;
  enabled: boolean;
}

export interface UsersConfig {
  users: UserRecord[];
}

const _emailRe = /^\S+@\S+\.\S+$/;

export function isValidEmail(s: unknown): boolean {
  return typeof s === "string" && s.length > 0 && s.length <= 254 && _emailRe.test(s);
}

export interface AuthContext {
  username: string;
  email?: string;
  global_admin: boolean;
  domains: Record<string, Permission>;
  // Set when the caller is the Open WebUI service token WITHOUT a valid
  // impersonation header. Such callers can list models (/v1/models fetches
  // are per-instance in Open WebUI, not per-user) but cannot generate chat
  // — the completions handler 403s on this flag.
  service_only?: boolean;
}

// ─────────────────────────────────────────────────────────────
// User store (file-backed, auto-reloading)
// ─────────────────────────────────────────────────────────────

let _users: Map<string, UserRecord> = new Map();
let _usersFile: string = "";
let _lastMtime: number = 0;

export function initUsers(config: Config): void {
  _usersFile = config.usersFile;
  _reloadIfChanged();
}

function _reloadIfChanged(): void {
  if (!_usersFile) return;
  try {
    const stat = Deno.statSync(_usersFile);
    const mtime = stat.mtime?.getTime() ?? 0;
    if (mtime <= _lastMtime) return;
    _lastMtime = mtime;

    const text = Deno.readTextFileSync(_usersFile);
    const data: UsersConfig = JSON.parse(text);
    const newMap = new Map<string, UserRecord>();
    for (const u of data.users) {
      if (u.enabled !== false) {
        newMap.set(u.key, u);
      }
    }
    _users = newMap;
    console.log(`Loaded ${_users.size} user(s) from ${_usersFile}`);
  } catch (e) {
    if (e instanceof Deno.errors.NotFound) {
      // File doesn't exist — single-key fallback mode
      return;
    }
    console.error(`Failed to load users file: ${e}`);
  }
}

function _resolveAuth(key: string, config: Config): AuthContext | null {
  // Reload if file changed
  _reloadIfChanged();

  // Try multi-user lookup
  const user = _users.get(key);
  if (user) {
    return {
      username: user.username,
      email: user.email,
      global_admin: user.global_admin,
      domains: user.domains,
    };
  }

  // Fallback: single-key mode (backwards compat). Closed once a real
  // global admin exists — brain-key then authenticates nothing.
  if (key === config.brainKey) {
    if (hasRealGlobalAdmin()) return null;
    return {
      username: "_admin",
      global_admin: true,
      domains: {},
    };
  }

  return null;
}

// ─────────────────────────────────────────────────────────────
// Permission checks
// ─────────────────────────────────────────────────────────────

const PERM_LEVELS: Record<Permission, number> = { read: 1, write: 2, admin: 3 };

export function hasPermission(
  auth: AuthContext,
  domain: string,
  required: Permission,
): boolean {
  if (auth.global_admin) return true;
  const granted = auth.domains[domain];
  if (!granted) return false;
  return PERM_LEVELS[granted] >= PERM_LEVELS[required];
}

// ─────────────────────────────────────────────────────────────
// Middleware factories
// ─────────────────────────────────────────────────��───────────

/**
 * MCP auth: reads x-brain-key header only.
 * MCP clients don't do cookies — keys only.
 */
export function mcpAuthMulti(config: Config): MiddlewareHandler {
  return async (c: Context, next) => {
    const key = c.req.header("x-brain-key");
    if (!key) return c.json({ error: "missing x-brain-key" }, 401);
    const auth = _resolveAuth(key, config);
    if (!auth) return c.json({ error: "invalid key" }, 401);
    c.set("auth", auth);
    await next();
  };
}

/**
 * Browser + API auth: accepts session cookie (from dashboard login) OR
 * Authorization: Bearer header (from API clients).
 *
 * Cookie is tried first — browser requests shouldn't need both.
 * Falls back to Bearer header for curl/CLI/OpenAI-compat consumers.
 *
 * Service-token impersonation: when Bearer matches the configured Open
 * WebUI service token, the request is required to also carry an
 * `X-OB2-User` header naming the user to act as. The impersonated user's
 * AuthContext is built and the request proceeds as if they called
 * directly. Service token alone (no header) is refused with 403.
 */
export function bearerAuthMulti(config: Config): MiddlewareHandler {
  return async (c: Context, next) => {
    // 1) Try session cookie
    const cookieHeader = c.req.header("cookie") || "";
    const match = cookieHeader.match(new RegExp(`(?:^|;\\s*)${SESSION_COOKIE_NAME}=([^;]+)`));
    if (match) {
      const session = await resolveSession(decodeURIComponent(match[1]));
      if (session) {
        const userAuth = _resolveAuthByUsername(session.username, config);
        if (userAuth) {
          c.set("auth", userAuth);
          await next();
          return;
        }
        // Session points to a deleted/disabled user — fall through to Bearer attempt
      }
    }

    // 2) Try Authorization: Bearer
    const header = c.req.header("authorization");
    if (header?.startsWith("Bearer ")) {
      const key = header.slice(7);

      // 2a) Service-token path. Two sub-cases:
      //   (a) With a valid impersonation header (X-OB2-User, or Open WebUI's
      //       forwarded X-OpenWebUI-User-Name when ENABLE_FORWARD_USER_INFO_HEADERS
      //       is on) → act as that user; full ACL applies.
      //   (b) Without one → "service_only" context. Can reach /v1/models so
      //       Open WebUI's per-instance model fetch succeeds, but /v1/chat/
      //       completions rejects it (chat always requires a real user).
      if (
        config.openwebuiServiceToken &&
        key === config.openwebuiServiceToken
      ) {
        const target =
          c.req.header("x-ob2-user") ||
          c.req.header("x-openwebui-user-name") ||
          "";
        if (target) {
          const impersonated = _resolveAuthByUsername(target, config);
          if (!impersonated) {
            return c.json({
              error: {
                message: "impersonation header names an unknown or disabled user",
                type: "authentication_error",
              },
            }, 403);
          }
          c.set("auth", impersonated);
          await next();
          return;
        }
        // No impersonation → service-only caller (model listing and other
        // read-only meta endpoints). Chat handler will 403 this flag.
        c.set("auth", {
          username: "_openwebui_service",
          global_admin: true,
          domains: {},
          service_only: true,
        });
        await next();
        return;
      }

      // 2b) Normal user API key (or single-key fallback)
      const auth = _resolveAuth(key, config);
      if (auth) {
        c.set("auth", auth);
        await next();
        return;
      }
    }

    return c.json({ error: "not authenticated" }, 401);
  };
}

/** Resolve auth context by username (used after session-cookie validation). */
function _resolveAuthByUsername(username: string, config: Config): AuthContext | null {
  _reloadIfChanged();
  // Single-key fallback user (created by login-with-brain-key). Gated by
  // the same predicate as _resolveAuth — if a real global admin exists,
  // any cached _admin cookie session resolves to null and the caller
  // gets a 401. Keeps the gate uniform across Bearer and cookie paths.
  if (username === "_admin") {
    if (hasRealGlobalAdmin()) return null;
    return { username: "_admin", global_admin: true, domains: {} };
  }
  for (const u of _users.values()) {
    if (u.username === username) {
      return { username: u.username, email: u.email, global_admin: u.global_admin, domains: u.domains };
    }
  }
  return null;
}

/**
 * Require a specific permission for a domain extracted from the request.
 * domainExtractor: function that pulls domain from the request (query param, body, url param).
 */
export function requireDomainPerm(
  required: Permission,
  domainExtractor: (c: Context) => string | null,
): MiddlewareHandler {
  return async (c: Context, next) => {
    const auth = c.get("auth") as AuthContext | undefined;
    if (!auth) return c.json({ error: "not authenticated" }, 401);
    const domain = domainExtractor(c);
    if (domain && !hasPermission(auth, domain, required)) {
      return c.json({
        error: `insufficient permissions: need '${required}' on @${domain}`,
        username: auth.username,
      }, 403);
    }
    await next();
  };
}

// ─────────────────────────────────────────────────────────────
// Admin: user management endpoints
// ────────────────────────────────────────────────────��────────

export function generateApiKey(): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  const hex = Array.from(bytes).map((b) => b.toString(16).padStart(2, "0")).join("");
  return `ob2_${hex}`;
}

/** True when users.json contains at least one enabled user with
 * global_admin=true. Used to gate the brain-key bootstrap — once a real
 * global admin exists, the brain-key stops authenticating anywhere. */
export function hasRealGlobalAdmin(): boolean {
  _reloadIfChanged();
  for (const u of _users.values()) {
    if (
      u.enabled !== false &&
      u.global_admin === true &&
      u.username !== "_admin"
    ) {
      return true;
    }
  }
  return false;
}

/** Internal: returns true if the proposed users array would have zero
 * enabled, non-_admin global admins. Used as a rail on writes that
 * demote, disable, or soft-delete users. */
function _wouldLeaveZeroAdmins(users: UserRecord[]): boolean {
  for (const u of users) {
    if (
      u.enabled !== false &&
      u.global_admin === true &&
      u.username !== "_admin"
    ) {
      return false;
    }
  }
  return true;
}

/** Thrown by updateUser/revokeUser/raw-save when the proposed state
 * would leave zero enabled global admins. The route layer translates
 * this to HTTP 409. */
export class ZeroAdminError extends Error {
  constructor() {
    super("refusing to save — would leave no enabled global admin");
    this.name = "ZeroAdminError";
  }
}

export function listUsers(): UserRecord[] {
  _reloadIfChanged();
  return Array.from(_users.values()).map((u) => ({
    ...u,
    key: u.key.slice(0, 8) + "..." + u.key.slice(-4),  // mask in listings
  }));
}

export function createUser(
  username: string,
  domains: Record<string, Permission>,
  global_admin: boolean = false,
  email?: string,
): UserRecord {
  if (email !== undefined && !isValidEmail(email)) {
    throw new Error("invalid email format");
  }
  const user: UserRecord = {
    username,
    key: generateApiKey(),
    global_admin,
    domains,
    created_at: new Date().toISOString(),
    enabled: true,
  };
  if (email) user.email = email.toLowerCase();

  const data = _loadFile();
  if (data.users.some((u) => u.username === username)) {
    throw new Error(`username '${username}' already exists`);
  }
  data.users.push(user);
  _atomicWrite(data);
  return user;
}

export interface UserPatch {
  domains?: Record<string, Permission>;
  global_admin?: boolean;
  email?: string | null;  // null = clear
}

export function updateUser(username: string, patch: UserPatch): UserRecord {
  const data = _loadFile();
  const idx = data.users.findIndex((u) => u.username === username);
  if (idx === -1) throw new Error(`user '${username}' not found`);
  const u = data.users[idx];
  // Simulate the patch in-place, then validate the rail, then commit.
  const prev = { domains: u.domains, global_admin: u.global_admin, email: u.email };
  if (patch.email !== undefined) {
    if (patch.email === null) {
      delete u.email;
    } else {
      if (!isValidEmail(patch.email)) {
        throw new Error("invalid email format");
      }
      u.email = patch.email.toLowerCase();
    }
  }
  if (patch.domains !== undefined) u.domains = patch.domains;
  if (patch.global_admin !== undefined) u.global_admin = patch.global_admin;
  if (_wouldLeaveZeroAdmins(data.users)) {
    // Roll back the in-memory mutation so _loadFile's contract (returns
    // current disk state) is preserved for any subsequent call.
    u.domains = prev.domains;
    u.global_admin = prev.global_admin;
    if (prev.email === undefined) delete u.email; else u.email = prev.email;
    throw new ZeroAdminError();
  }
  _atomicWrite(data);
  return { ...u, key: u.key.slice(0, 8) + "..." + u.key.slice(-4) };
}

export function revokeUser(username: string): UserRecord {
  const data = _loadFile();
  const idx = data.users.findIndex((u) => u.username === username);
  if (idx === -1) throw new Error(`user '${username}' not found`);
  const prev = data.users[idx].enabled;
  data.users[idx].enabled = false;
  if (_wouldLeaveZeroAdmins(data.users)) {
    data.users[idx].enabled = prev;
    throw new ZeroAdminError();
  }
  _atomicWrite(data);
  return { ...data.users[idx], key: "***revoked***" };
}

/** Set or replace a user's password (argon2id hash stored). */
export async function setPassword(username: string, password: string): Promise<void> {
  const data = _loadFile();
  const idx = data.users.findIndex((u) => u.username === username);
  if (idx === -1) throw new Error(`user '${username}' not found`);
  data.users[idx].password_hash = await hashPassword(password);
  _atomicWrite(data);
}

/** Verify a (username, password) login attempt. Returns the user record on
 * success, null on any failure (including unknown user, disabled user, or
 * missing/wrong password). Constant-time at the argon2 level. */
export async function verifyPassword(username: string, password: string): Promise<UserRecord | null> {
  _reloadIfChanged();
  const data = _loadFile();
  const user = data.users.find((u) => u.username === username);
  if (!user || user.enabled === false || !user.password_hash) return null;
  const ok = await verifyHash(user.password_hash, password);
  return ok ? user : null;
}

/** Rotate a user's API key. Returns the new (full, plain) key — shown once. */
export function rotateApiKey(username: string): string {
  const data = _loadFile();
  const idx = data.users.findIndex((u) => u.username === username);
  if (idx === -1) throw new Error(`user '${username}' not found`);
  const newKey = generateApiKey();
  data.users[idx].key = newKey;
  _atomicWrite(data);
  return newKey;
}

/** Set or clear a user's recovery email. Pass null to clear. */
export function setEmail(username: string, email: string | null): UserRecord {
  const data = _loadFile();
  const idx = data.users.findIndex((u) => u.username === username);
  if (idx === -1) throw new Error(`user '${username}' not found`);
  if (email === null) {
    delete data.users[idx].email;
  } else {
    if (!isValidEmail(email)) throw new Error("invalid email format");
    data.users[idx].email = email.toLowerCase();
  }
  _atomicWrite(data);
  const u = data.users[idx];
  return { ...u, key: u.key.slice(0, 8) + "..." + u.key.slice(-4) };
}

/** Look up a user by their registered email address. Returns the full record
 * (with plaintext key) — callers must not expose it directly. */
export function findUserByEmail(email: string): UserRecord | null {
  _reloadIfChanged();
  for (const u of _users.values()) {
    if (u.email && u.email.toLowerCase() === email.toLowerCase()) {
      return u;
    }
  }
  return null;
}

function _loadFile(): UsersConfig {
  try {
    const text = Deno.readTextFileSync(_usersFile);
    return JSON.parse(text) as UsersConfig;
  } catch (e) {
    if (e instanceof Deno.errors.NotFound) return { users: [] };
    throw e;
  }
}

function _atomicWrite(data: UsersConfig): void {
  // Write to temp + rename for atomicity — prevents partial file on crash
  const tmp = `${_usersFile}.tmp.${Date.now()}`;
  Deno.writeTextFileSync(tmp, JSON.stringify(data, null, 2));
  Deno.renameSync(tmp, _usersFile);
  _lastMtime = 0; // force reload on next call
  _reloadIfChanged();
}

/** Raised by saveRawUsersFile when on-disk mtime disagrees with
 * the caller's expected_mtime. The route layer translates to 409. */
export class RawMtimeConflictError extends Error {
  constructor() {
    super("users.json was modified by someone else — reload and retry");
    this.name = "RawMtimeConflictError";
  }
}

/** Return users.json verbatim, plus its on-disk path and mtime
 * (ISO-8601). Used by the raw editor UI to seed a round-trip edit. */
export function getRawUsersFile(): { content: string; path: string; mtime: string } {
  const text = Deno.readTextFileSync(_usersFile);
  const stat = Deno.statSync(_usersFile);
  const mtime = (stat.mtime ?? new Date(0)).toISOString();
  return { content: text, path: _usersFile, mtime };
}

/** Validate + write users.json in one shot. Returns the fresh mtime on
 * success. Throws:
 *   - SyntaxError: invalid JSON (route → 400)
 *   - TypeError:   schema violation (route → 400)
 *   - ZeroAdminError: would leave zero enabled global admins (route → 400)
 *   - RawMtimeConflictError: on-disk mtime differs (route → 409) */
export function saveRawUsersFile(
  content: string,
  expectedMtime: string,
): { mtime: string; previouslyHadRealAdmin: boolean; nowHasRealAdmin: boolean } {
  // 1. Parse
  let parsed: unknown;
  try {
    parsed = JSON.parse(content);
  } catch (e) {
    throw new SyntaxError(`invalid JSON: ${(e as Error).message}`);
  }
  if (
    !parsed ||
    typeof parsed !== "object" ||
    !Array.isArray((parsed as UsersConfig).users)
  ) {
    throw new TypeError("expected shape { users: [...] }");
  }
  const next = (parsed as UsersConfig).users;

  // 2. Schema validate
  const validPerms = new Set(["read", "write", "admin"]);
  for (const [i, u] of next.entries()) {
    if (!u || typeof u !== "object") {
      throw new TypeError(`users[${i}]: expected object`);
    }
    if (typeof u.username !== "string" || u.username.length === 0) {
      throw new TypeError(`users[${i}].username: required non-empty string`);
    }
    if (u.domains && typeof u.domains === "object") {
      for (const [d, p] of Object.entries(u.domains)) {
        if (!validPerms.has(p as string)) {
          throw new TypeError(
            `users[${i}].domains["${d}"]: must be read|write|admin`,
          );
        }
      }
    }
    if (u.email !== undefined && !isValidEmail(u.email)) {
      throw new TypeError(`users[${i}].email: invalid format`);
    }
  }

  // 3. Zero-admin rail (reuses the same predicate updateUser/revokeUser use)
  if (_wouldLeaveZeroAdmins(next)) {
    throw new ZeroAdminError();
  }

  // 4. mtime conflict check
  const stat = Deno.statSync(_usersFile);
  const currentMtime = (stat.mtime ?? new Date(0)).toISOString();
  if (currentMtime !== expectedMtime) {
    throw new RawMtimeConflictError();
  }

  // 5. Capture bootstrap-gate transition for the caller (so the route
  // can evict _admin sessions if promotion happened via raw save).
  const previouslyHadRealAdmin = hasRealGlobalAdmin();

  // 6. Atomic write + reload
  _atomicWrite({ users: next });

  const nowHasRealAdmin = hasRealGlobalAdmin();
  const newStat = Deno.statSync(_usersFile);
  return {
    mtime: (newStat.mtime ?? new Date()).toISOString(),
    previouslyHadRealAdmin,
    nowHasRealAdmin,
  };
}
